---
version: "3"
services:
  db:
    image: mysql:5.6
    ports:
      - "13306:3306"
    volumes:
      - "./files/etc/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./scripts/db:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: sandbox
      MYSQL_ROOT_PASSWORD: password
